### PR TITLE
feat: render `progname` as `program` in default logger backend

### LINKED ISSUE #43: Travis CI no longer functions
For full log please view here https://travis-ci.org/github/spider-gazelle/action-controller/builds/770617223

### LINKED ISSUE #44: Remove use of `NilLiteral.nil?`
As of this [PR](https://github.com/crystal-lang/crystal/pull/10616), this [line of code fails](https://github.com/spider-gazelle/action-controller/blob/12107cfd7e7c1767a23c8ef106d54afe5060fcca/src/action-controller/base.cr#L554).

Removing the `.nil?` check will do the trick

### PR DESCRIPTION
**Pull request by caspiano**
Renders the `progname` property of the logger as `program` in the JSON and IO based log backend

- Adds github CI, Closes #43
- Fixes #44

### CODE REVIEW

**Comment by caspiano** [comment]
Fixes #44 
Closes #43

**Review by dukeraphaelng — APPROVED** [review]
I don't exactly understand why we are rendering progname as program? other than that lgtm

**Comment by caspiano** [comment]
`progname` to me sounded weird, so i've rendered it as `program`. happy to change it if it doesn't make sense

**Comment by dukeraphaelng** [comment]
I see. so it's just word usage. thats all good then

**Pull request merged**
